# Generated by Django 5.2.9 on 2025-12-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallTicketExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=10)),
                ('course_code', models.CharField(max_length=50)),
                ('course_title', models.CharField(max_length=200)),
                ('exam_date', models.DateField()),
                ('session', models.CharField(max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Hall Ticket Exam',
                'verbose_name_plural': 'Hall Ticket Exams',
                'ordering': ['exam_date', 'session'],
            },
        ),
    ]
