# Generated by Django 5.2.9 on 2025-12-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_hallticketexam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hallticketexam',
            name='course_code',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='hallticketexam',
            name='course_title',
            field=models.CharField(max_length=300),
        ),
    ]
